# Generated by Django 3.2.4 on 2021-07-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_my_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_stations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
