# Generated by Django 3.2.4 on 2021-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoppointid', models.IntegerField()),
                ('stop_name', models.CharField(max_length=45)),
                ('stop_lat', models.FloatField()),
                ('stop_long', models.FloatField()),
                ('direction', models.IntegerField()),
                ('routes_serving', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NameToID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=45)),
                ('stop_name', models.CharField(max_length=45)),
                ('stop_lat', models.FloatField()),
                ('stop_long', models.FloatField()),
                ('stop_num', models.IntegerField()),
            ],
        ),
    ]
