# Generated by Django 3.2.4 on 2021-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoppointid', models.IntegerField()),
                ('stop_name', models.CharField(max_length=45)),
                ('stop_lat', models.FloatField()),
                ('stop_long', models.FloatField()),
                ('direction', models.IntegerField()),
                ('routes_serving', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BikeStation',
        ),
    ]
