# Generated by Django 3.2.4 on 2021-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBusRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapeid', models.CharField(blank=True, db_column='ShapeID', max_length=20, null=True)),
                ('stopsequence', models.IntegerField(blank=True, db_column='StopSequence', null=True)),
                ('routename', models.CharField(blank=True, db_column='RouteName', max_length=10, null=True)),
                ('routedescription', models.CharField(blank=True, db_column='RouteDescription', max_length=40, null=True)),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=5, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('shortcommonname_en', models.CharField(blank=True, db_column='ShortCommonName_en', max_length=40, null=True)),
                ('haspole', models.CharField(blank=True, db_column='HasPole', max_length=20, null=True)),
                ('hasshelter', models.CharField(blank=True, db_column='HasShelter', max_length=20, null=True)),
                ('routedata', models.CharField(blank=True, db_column='RouteData', max_length=50, null=True)),
                ('route', models.CharField(db_column='Route', max_length=10)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=45, null=True)),
            ],
            options={
                'db_table': 'all_bus_routes',
                'managed': False,
            },
        ),
    ]
