# Generated by Django 3.2.4 on 2021-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=45)),
                ('agency_id', models.CharField(max_length=45)),
                ('route_short_name', models.CharField(max_length=45)),
                ('route_long_name', models.CharField(max_length=45)),
                ('route_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusShapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=45)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
                ('shape_dist_traveled', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=45)),
                ('stop_name', models.CharField(max_length=45)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusStopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=45)),
                ('arrival_time', models.CharField(max_length=45)),
                ('departure_time', models.CharField(max_length=45)),
                ('stop_id', models.CharField(max_length=45)),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(max_length=45)),
                ('pickup_type', models.IntegerField()),
                ('drop_off_type', models.IntegerField()),
                ('shape_dist_traveled', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusTransfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_id', models.CharField(max_length=45)),
                ('to_stop_id', models.CharField(max_length=45)),
                ('transfer_type', models.IntegerField()),
                ('min_transfer_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=45)),
                ('service_id', models.CharField(max_length=45)),
                ('trip_id', models.CharField(max_length=45)),
                ('shape_id', models.CharField(max_length=45)),
                ('trip_headsign', models.CharField(max_length=45)),
                ('direction_id', models.IntegerField()),
            ],
        ),
    ]
