# Generated by Django 3.2.4 on 2021-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_busroutes_busshapes_busstops_busstoptimes_bustransfers_bustrips'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShapeID', models.CharField(max_length=45)),
                ('StopSequence', models.IntegerField()),
                ('RouteName', models.CharField(max_length=45)),
                ('RouteDescription', models.CharField(max_length=45)),
                ('Direction', models.CharField(max_length=45)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('ShortCommonName_en', models.CharField(max_length=45)),
                ('HasPole', models.CharField(max_length=45)),
                ('HasShelter', models.CharField(max_length=45)),
                ('RouteData', models.CharField(max_length=45)),
            ],
        ),
    ]
