# Generated by Django 3.2.4 on 2021-06-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_allbusroutes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allbusroutes',
            table='map_all_bus_routes',
        ),
    ]
