# Generated by Django 3.2.4 on 2021-06-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_allbusroutes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allbusroutes',
            table='all_bus_routes',
        ),
    ]
