# Generated by Django 3.2.4 on 2021-06-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_allbusroutes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAllroutedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapeid', models.IntegerField(blank=True, db_column='ShapeID', null=True)),
                ('stopsequence', models.CharField(blank=True, db_column='StopSequence', max_length=45, null=True)),
                ('atcocode', models.CharField(blank=True, db_column='AtcoCode', max_length=45, null=True)),
                ('routename', models.CharField(blank=True, db_column='RouteName', max_length=45, null=True)),
                ('routedesc', models.CharField(blank=True, db_column='RouteDesc', max_length=45, null=True)),
                ('direction', models.CharField(blank=True, db_column='Direction', max_length=45, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=45, null=True)),
                ('shortcommonname_en', models.CharField(blank=True, db_column='ShortCommonName_en', max_length=45, null=True)),
                ('haspole', models.CharField(blank=True, db_column='HasPole', max_length=45, null=True)),
                ('hasshelter', models.CharField(blank=True, db_column='HasShelter', max_length=45, null=True)),
                ('routedata', models.CharField(blank=True, db_column='RouteData', max_length=45, null=True)),
                ('route', models.CharField(db_column='Route', max_length=10)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=45, null=True)),
            ],
            options={
                'db_table': 'MAP_allroutedata',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AllBusRoutes',
        ),
    ]
