# Generated by Django 3.2.4 on 2021-06-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20210620_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapAllroutedata',
        ),
    ]
