# Generated by Django 3.2.4 on 2021-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_delete_mapallroutedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutesDayModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeid', models.CharField(blank=True, db_column='routeID', max_length=45, null=True)),
                ('progrnum', models.FloatField(blank=True, null=True)),
                ('bus_lineid', models.CharField(blank=True, db_column='bus_lineID', max_length=45, null=True)),
                ('stoppointid', models.CharField(blank=True, db_column='stoppointID', max_length=22, null=True)),
                ('direction', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_long', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_lat', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'routes_day_models',
                'managed': False,
            },
        ),
    ]
