# Generated by Django 3.2.4 on 2021-06-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_routesdaymodels'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='routesdaymodels',
            table='dubbusdb.routes_day_models',
        ),
    ]
