# Generated by Django 3.2.4 on 2021-07-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210628_1158'),
        ('map', '0008_alter_routesdaymodels_table'),
    ]

    operations = [
    ]
