# Generated by Django 3.2.4 on 2021-07-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_merge_20210702_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('bk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bk_contract_name', models.CharField(max_length=45)),
                ('bk_name', models.CharField(max_length=45)),
                ('bk_address', models.CharField(max_length=45)),
                ('bk_lat', models.FloatField()),
                ('bk_lng', models.FloatField()),
                ('bk_banking', models.CharField(max_length=45)),
                ('bk_bouns', models.CharField(max_length=45)),
                ('bk_bike_stands', models.IntegerField()),
                ('bk_available_bike_stands', models.IntegerField()),
                ('bk_available_bikes', models.IntegerField()),
                ('bk_status', models.CharField(max_length=45)),
                ('bk_last_update', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.TextField(default='', max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='my_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_stop', models.CharField(max_length=50)),
                ('end_stop', models.CharField(max_length=50)),
                ('latitude1', models.FloatField()),
                ('longitude1', models.FloatField()),
                ('latitude2', models.FloatField()),
                ('longitude2', models.FloatField()),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.myuser')),
            ],
        ),
    ]
