# Generated by Django 3.2.4 on 2021-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_bikestation_my_plans_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_plans',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
