# Generated by Django 3.2.4 on 2021-07-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_bikestation_my_plans_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameToID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=45)),
                ('stop_name', models.CharField(max_length=45)),
                ('stop_lat', models.FloatField()),
                ('stop_long', models.FloatField()),
                ('stop_num', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BikeStation',
        ),
        migrations.RemoveField(
            model_name='my_plans',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoutesDayModels',
        ),
        migrations.DeleteModel(
            name='my_plans',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
