# Generated by Django 3.2.4 on 2021-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopTimesGoogle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_id', models.CharField(blank=True, max_length=45, null=True)),
                ('arr_time', models.CharField(blank=True, max_length=45, null=True)),
                ('dep_time', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stopp_seq', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_off_type', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'stop_times_google',
                'managed': False,
            },
        ),
    ]
