# Generated by Django 3.2.4 on 2021-07-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StopTimesGoogle',
        ),
    ]
