# Generated by Django 3.2.4 on 2021-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AA_Road_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('location', models.TextField()),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='currentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField()),
                ('time', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.CharField(max_length=45)),
                ('uvi', models.TextField(max_length=50)),
                ('feels_like', models.TextField(max_length=50)),
                ('pressure', models.TextField(max_length=50)),
                ('humidity', models.TextField(max_length=50)),
                ('wind_speed', models.TextField(max_length=50)),
                ('cloudy', models.TextField(max_length=50)),
                ('mainweather', models.TextField(max_length=50)),
                ('time_added', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.TextField()),
                ('temp', models.TextField()),
                ('temp_max', models.TextField()),
                ('temp_min', models.TextField()),
                ('feelslike', models.TextField()),
                ('pressure', models.FloatField()),
                ('humidity', models.CharField(max_length=45)),
                ('main', models.TextField(max_length=50)),
                ('wind_speed', models.TextField(max_length=50)),
                ('wind_deg', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
