# Generated by Django 3.2.4 on 2021-06-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField()),
                ('time', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.CharField(max_length=45)),
                ('uvi', models.TextField(max_length=50)),
                ('feels_like', models.TextField(max_length=50)),
                ('pressure', models.TextField(max_length=50)),
                ('humidity', models.TextField(max_length=50)),
                ('wind_speed', models.TextField(max_length=50)),
                ('cloudy', models.TextField(max_length=50)),
                ('mainweather', models.TextField(max_length=50)),
                ('time_added', models.CharField(max_length=45)),
            ],
        ),
    ]
