# Generated by Django 3.2.4 on 2021-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.TextField()),
                ('ffeelslike', models.TextField()),
                ('fpressure', models.FloatField()),
                ('fhumidity', models.CharField(max_length=45)),
                ('fmain', models.TextField(max_length=50)),
                ('fwind_speed', models.TextField(max_length=50)),
                ('pressure', models.TextField(max_length=50)),
            ],
        ),
    ]
