# Generated by Django 3.2.4 on 2021-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AA_Road_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('location', models.TextField()),
                ('report', models.TextField()),
            ],
        ),
    ]
