# Generated by Django 3.2.4 on 2021-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_aa_road_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='ffeelslike',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='fhumidity',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='fmain',
            new_name='main',
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='fwind_speed',
            new_name='wind_speed',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='fpressure',
        ),
        migrations.AddField(
            model_name='forecast',
            name='feelslike',
            field=models.TextField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='temp',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='temp_max',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='temp_min',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='wind_deg',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecast',
            name='pressure',
            field=models.FloatField(),
        ),
    ]
